package com.google.android.apps.androidify.a;

public class j {
    public float A;
    public float B;
    public float C;
    public float D;
    public float E;
    public float F;
    public float G;
    public float H;
    public float I;
    public float J;
    public float K;
    public float L;
    public float M;
    public float N;
    public float O;
    public float P;
    public float Q;
    public float R;
    public boolean S;
    public boolean T;
    public e U;
    private boolean V;
    public float a;
    public float b;
    public float c;
    public float d;
    public float e;
    public float f;
    public float g;
    public float h;
    public float i;
    public float j;
    public float k;
    public float l;
    public float m;
    public float n;
    public float o;
    public float p;
    public float q;
    public float r;
    public float s;
    public float t;
    public float u;
    public float v;
    public float w;
    public float x;
    public float y;
    public float z;

    public j() {
        this.a = 0.0f;
        this.b = 0.0f;
        this.c = 0.0f;
        this.d = 0.0f;
        this.e = 0.0f;
        this.f = 0.0f;
        this.g = 0.0f;
        this.h = 0.0f;
        this.i = 0.0f;
        this.j = 0.0f;
        this.k = 0.0f;
        this.l = 0.0f;
        this.m = 0.0f;
        this.n = 0.0f;
        this.o = 0.0f;
        this.p = 0.0f;
        this.q = 0.0f;
        this.r = 0.0f;
        this.s = 0.0f;
        this.t = 0.0f;
        this.u = 0.0f;
        this.v = 0.0f;
        this.w = 0.0f;
        this.x = 0.0f;
        this.y = 0.0f;
        this.z = 0.0f;
        this.A = 0.0f;
        this.B = 0.0f;
        this.C = 0.0f;
        this.D = 0.0f;
        this.E = 0.0f;
        this.F = 0.0f;
        this.G = 0.0f;
        this.H = 0.0f;
        this.I = 0.0f;
        this.J = 0.0f;
        this.K = 1.0f;
        this.L = 1.0f;
        this.M = 1.0f;
        this.N = 1.0f;
        this.O = 1.0f;
        this.P = 1.0f;
        this.Q = 1.0f;
        this.R = 1.0f;
        this.V = true;
        this.S = false;
        this.T = true;
        this.U = null;
    }

    public void a() {
        this.U = null;
        this.T = true;
        this.i = 0.0f;
        this.a = 0.0f;
        this.b = 0.0f;
        this.c = 0.0f;
        this.d = 0.0f;
        this.j = 0.0f;
        this.k = 0.0f;
        this.o = 0.0f;
        this.p = 0.0f;
        this.q = 0.0f;
        this.r = 0.0f;
        this.w = 0.0f;
        this.x = 0.0f;
        this.y = 0.0f;
        this.z = 0.0f;
        this.K = 1.0f;
        this.L = 1.0f;
        this.C = 0.0f;
        this.D = 0.0f;
        this.M = 1.0f;
        this.N = 1.0f;
        this.E = 0.0f;
        this.F = 0.0f;
        this.G = 0.0f;
        this.H = 0.0f;
        this.n = 0.0f;
        this.I = 0.0f;
        this.J = 0.0f;
        this.O = 1.0f;
        this.P = 1.0f;
        this.g = 0.0f;
        this.h = 0.0f;
        this.e = 0.0f;
        this.f = 0.0f;
        this.A = 0.0f;
        this.B = 0.0f;
        this.Q = 1.0f;
        this.k = 0.0f;
    }

    public void a(e eVar, j jVar, float f, double d, float f2) {
        this.T = false;
        this.U = eVar;
        if (this.V) {
            d = (eVar.d() + d) % eVar.b();
        }
        this.i = eVar.a(d, h.HEAD_ROTATE);
        this.a = eVar.a(d, h.LEFT_SHOULDER_ROTATE);
        this.b = -eVar.a(d, h.RIGHT_SHOULDER_ROTATE);
        this.c = eVar.a(d, h.LEFT_HIP_ROTATE);
        this.d = -eVar.a(d, h.RIGHT_HIP_ROTATE);
        this.e = eVar.a(d, h.LEFT_FOOT_ROTATE);
        this.f = -eVar.a(d, h.RIGHT_FOOT_ROTATE);
        this.g = eVar.a(d, h.LEFT_ANTENNA_ROTATE);
        this.h = -eVar.a(d, h.RIGHT_ANTENNA_ROTATE);
        this.j = eVar.a(d, h.BODY_ROTATE);
        this.k = eVar.a(d, h.MASTER_ROTATE);
        this.l = eVar.a(d, h.LEFT_EYE_ROTATION);
        this.m = -eVar.a(d, h.RIGHT_EYE_ROTATION);
        this.n = eVar.a(d, h.PROP_ROTATE);
        this.o = ((eVar.a(d, h.LEFT_SHOULDER_POSITION_X) * 1.0f) * 0.25714287f) * this.R;
        this.p = (((-eVar.a(d, h.LEFT_SHOULDER_POSITION_Y)) * 1.0f) * 0.25714287f) * this.R;
        this.q = (((-eVar.a(d, h.RIGHT_SHOULDER_POSITION_X)) * 1.0f) * 0.25714287f) * this.R;
        this.r = (((-eVar.a(d, h.RIGHT_SHOULDER_POSITION_Y)) * 1.0f) * 0.25714287f) * this.R;
        this.w = (eVar.a(d, h.HEAD_POSITION_X) * 1.0f) * this.R;
        this.x = (eVar.a(d, h.HEAD_POSITION_Y) * 1.0f) * this.R;
        this.y = ((eVar.a(d, h.BODY_POSITION_X) * 1.0f) * 1.0f) * this.R;
        this.z = ((eVar.a(d, h.BODY_POSITION_Y) * 1.0f) * 1.0f) * this.R;
        this.A = ((eVar.a(d, h.MASTER_POSITION_X) * 1.0f) * 1.0f) * this.R;
        this.B = ((eVar.a(d, h.MASTER_POSITION_Y) * 1.0f) * 1.0f) * this.R;
        this.C = ((eVar.a(d, h.EYES_POSITION_X) * 1.0f) * 1.0f) * this.R;
        this.D = ((eVar.a(d, h.EYES_POSITION_Y) * 1.0f) * 1.0f) * this.R;
        this.E = ((eVar.a(d, h.BLINK_LEFT_POSITION_X) * 1.0f) * 1.0f) * this.R;
        this.F = ((eVar.a(d, h.BLINK_LEFT_POSITION_Y) * 1.0f) * 1.0f) * this.R;
        this.G = (((-eVar.a(d, h.BLINK_RIGHT_POSITION_X)) * 1.0f) * 1.0f) * this.R;
        this.H = ((eVar.a(d, h.BLINK_RIGHT_POSITION_Y) * 1.0f) * 1.0f) * this.R;
        this.I = ((eVar.a(d, h.PROP_POSITION_X) * 1.0f) * this.R) * 1.0f;
        this.J = ((eVar.a(d, h.PROP_POSITION_Y) * 1.0f) * this.R) * 1.0f;
        this.K = eVar.a(d, h.LEFT_EYE_SCALE) / 100.0f;
        this.L = eVar.a(d, h.RIGHT_EYE_SCALE) / 100.0f;
        this.M = eVar.a(d, h.BLINK_LEFT_SCALE) / 100.0f;
        this.N = eVar.a(d, h.BLINK_RIGHT_SCALE) / 100.0f;
        this.P = eVar.a(d, h.PROP_SCALE_X) / 100.0f;
        this.O = eVar.a(d, h.PROP_SCALE_Y) / 100.0f;
        this.Q = eVar.a(d, h.MASTER_SCALE) / 100.0f;
        if (jVar != null) {
            this.i = (this.i * f) + ((1.0f - f) * jVar.i);
            this.a = (this.a * f) + ((1.0f - f) * jVar.a);
            this.b = (this.b * f) + ((1.0f - f) * jVar.b);
            this.c = (this.c * f) + ((1.0f - f) * jVar.c);
            this.d = (this.d * f) + ((1.0f - f) * jVar.d);
            this.e = (this.e * f) + ((1.0f - f) * jVar.e);
            this.f = (this.f * f) + ((1.0f - f) * jVar.f);
            this.g = (this.g * f) + ((1.0f - f) * jVar.g);
            this.h = (this.h * f) + ((1.0f - f) * jVar.h);
            this.j = (this.j * f) + ((1.0f - f) * jVar.j);
            this.k = (this.k * f) + ((1.0f - f) * jVar.k);
            this.l = (this.l * f) + ((1.0f - f) * jVar.l);
            this.m = (this.m * f) + ((1.0f - f) * jVar.m);
            this.o = (this.o * f) + ((1.0f - f) * jVar.o);
            this.p = (this.p * f) + ((1.0f - f) * jVar.p);
            this.q = (this.q * f) + ((1.0f - f) * jVar.q);
            this.r = (this.r * f) + ((1.0f - f) * jVar.r);
            this.w = (this.w * f) + ((1.0f - f) * jVar.w);
            this.x = (this.x * f) + ((1.0f - f) * jVar.x);
            this.y = (this.y * f) + ((1.0f - f) * jVar.y);
            this.z = (this.z * f) + ((1.0f - f) * jVar.z);
            this.A = (this.A * f) + ((1.0f - f) * jVar.A);
            this.B = (this.B * f) + ((1.0f - f) * jVar.B);
            this.C = (this.C * f) + ((1.0f - f) * jVar.C);
            this.D = (this.D * f) + ((1.0f - f) * jVar.D);
            this.E = (this.E * f) + ((1.0f - f) * jVar.E);
            this.F = (this.F * f) + ((1.0f - f) * jVar.F);
            this.G = (this.G * f) + ((1.0f - f) * jVar.G);
            this.H = (this.H * f) + ((1.0f - f) * jVar.H);
            this.K = (this.K * f) + ((1.0f - f) * jVar.K);
            this.L = (this.L * f) + ((1.0f - f) * jVar.L);
            this.M = (this.M * f) + ((1.0f - f) * jVar.M);
            this.N = (this.N * f) + ((1.0f - f) * jVar.N);
            if (this.S) {
                this.I = (this.I * f) + ((1.0f - f) * jVar.I);
                this.J = (this.J * f) + ((1.0f - f) * jVar.J);
                this.n = (this.n * f) + ((1.0f - f) * jVar.n);
                this.P = (this.P * f) + ((1.0f - f) * jVar.P);
                this.O = (this.O * f) + ((1.0f - f) * jVar.O);
            } else {
                this.P *= f;
                this.O *= f;
            }
            this.Q = (this.Q * f) + ((1.0f - f) * jVar.Q);
        }
    }

    public void a(boolean z) {
        this.V = z;
    }
}
